### ISSUE TITLE
Request: individual positioning of hp, mp, tp bars and text.

### ISSUE THREAD

**Issue by Erebos333** [Tylas11/XivParty#12]
I want a more feature-rich version of the original ffxi party list. which means being able to move the mp bar below the hp bar. pic of someone that already did it.
![ItGdEmz](https://user-images.githubusercontent.com/44206820/173181657-8ea2de7e-fd34-41ae-bdb4-51dc9dc142b7.png)
.

**Comment by Tylas11** [comment]
At the moment some of the elements' positions are relative to each other. I know it is not ideal, as it limits how much you can customize the layout. The main reason (other than less work) was to keep the layout XMLs shorter and easier to understand.

I'll consider your suggestion for the next big update that changes the UI, however this will most likely mean old XMLs for user created layouts will no longer be compatible.

**Comment by Tylas11** [comment]
Added in release 2.0.0.
