### ISSUE TITLE
Clickable partylist?

### ISSUE THREAD

**Issue by seathasky** [Tylas11/XivParty#13]
Can we have an option to make the party list clickable like Ashita's "Greed" plugin?
https://docs.ashitaxi.com/plugins/greed/

Basically click a party member or self to target said player. I'm a keyboard and mouse player and this would be extremely helpful!

Healer woes man!

**Comment by Tylas11** [comment]
This request has only come up once before, but it seems there is more interest in it.
I will add it to my ToDo list.

**Comment by seathasky** [comment]
Thank you soo much Tylas! You're a champ! As a healer this would be amazing! I'll keep a lookout for any updates <3

**Comment by Tylas11** [comment]
Added in release 2.0.0.
