### ISSUE TITLE
Request: Party Distance

### ISSUE THREAD

**Issue by Heretic6667** [Tylas11/XivParty#16]
I know range indicator is a thing, but I was hoping for something more numerical.  Any chance something similar to what Kenshi did for TParty could be incoporated into XivParty?

https://github.com/KenshiDRK/Addons/tree/master/TParty

![image](https://user-images.githubusercontent.com/65053603/215670553-98d0aaab-c4ea-428f-a4ad-52ce1735c0c4.png)

thanks,

**Comment by Tylas11** [comment]
Will be added in the next minor release.

**Comment by Tylas11** [comment]
Has been added to release 2.1.0. Activate using "//xp range num". Available in all layouts except ffxi2 by default.
