### ISSUE TITLE
Ashita

### ISSUE THREAD

**Issue by Lynnea1320** [Tylas11/XivParty#17]
Can we please get this on Ashita, I will love you long time.

**Comment by Tylas11** [comment]
Tirem ported it to Ashita recently: https://github.com/tirem/XivParty
Now you have to love us both long time! :3

**Comment by Lynnea1320** [comment]
Ooh hopefully simultaneously :D

**Comment by bahamut44** [comment]
Is it possible this can be used on private server? I play on eden and when i try to load it i get: Failed to load addon file xivparty. Error: \addons\xivparty\sivparty.lua:768: nesting of [[...]] is deprecated near '['

I tried all the different release versions and got that same message, although the number changed a bit.

**Comment by Tylas11** [comment]
You will have to ask tirem (see gibhub link above), as he maintains the Ashita version. I do not use private servers or Ashita so I won't be much help. However I do not think a private server or even a different client version would cause such an error. You might want to update Ashita itself to the latest version though.

**Comment by bahamut44** [comment]
Oh, ok. I thought I put this on his page. My mistake, thanks for your response.
