### ISSUE TITLE
I followed your instructions precisely. It still won't load.

### ISSUE THREAD

**Issue by btannen000** [Tylas11/XivParty#2]
I put XivParty in the addons folder. But when I load the game, it loads everything else in the addons folders, not XivParty. So, I try manually to

lua load XivParty

and it says: Error loading Xivparty: file does not exist.

It is EXACTLY in the addons folder, I see it there myself. but this Windower isn't recognizing it at all.

Please help! This healer needs this addon!!

**Comment by Tylas11** [comment]
Windower will try to load windower4/addons/xivparty/xivparty.lua. If the file is anywhere else, you will get that "file does not exist" error.
Download the latest release zip file and extract it into windower4/addons, it already contains the xivparty directory.
