### ISSUE TITLE
How do I hide mp bar?

### ISSUE THREAD

**Issue by CLDR1** [Tylas11/XivParty#6]
I would like to know how would I be able to hide the mp bar and only have HP + status?

I mainly ask because I use it as a main whm

**Comment by Tylas11** [comment]
There is no easy way to do this.
If you have lua programming experience you can edit listitem.lua and remove all lines mentioning mpBar and tpBar. However, some other elements like the buffs and zone names align to the TP bar, using 'tpPosX'. You'll need to set new positions for those elements and make sure they dont overlap with the character names for example.
