### ISSUE TITLE
Request/Suggestion: Hide self

### ISSUE THREAD

**Issue by andre-macc** [Tylas11/XivParty#7]
By looking at the code I don't know if this is possible: For those of us who use XIVBar, an option to hide your own information in XIVParty would be interesting.

**Comment by Tylas11** [comment]
It is certainly possible, you just need to make it skip the first list item in view.lua and adjust the background position a bit.
However neither the ffxi nor the ffxiv party lists work that way, so I do not intend to add this as a feature.

**Comment by andre-macc** [comment]
> It is certainly possible, you just need to make it skip the first list item in view.lua and adjust the background position a bit.
> However neither the ffxi nor the ffxiv party lists work that way, so I do not intend to add this as a feature.

Thanks for the answer, I'm still new to windower addons coding so I appreciate the tip on how to do it myself.
